//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.29 at 05:03:04 PM IST 
//


package abc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QA" type="{abc}QA"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qa"
})
@XmlRootElement(name = "getAnswerResponse")
public class GetAnswerResponse {

    @XmlElement(name = "QA", required = true)
    protected QA qa;

    /**
     * Gets the value of the qa property.
     * 
     * @return
     *     possible object is
     *     {@link QA }
     *     
     */
    public QA getQA() {
        return qa;
    }

    /**
     * Sets the value of the qa property.
     * 
     * @param value
     *     allowed object is
     *     {@link QA }
     *     
     */
    public void setQA(QA value) {
        this.qa = value;
    }

}
